### ISSUE TITLE
Fix Broken Pre-registering.

### ISSUE THREAD

**Issue by RintaDev5792** [OceanUwU/battlebot#4]
Pre-registering for the next game either says it doesn't work or "you've already pre-registered". Please fix this.

**Comment by OceanUwU** [comment]
```
BOT: rintadev ran /preregister
DiscordAPIError[50035]: Invalid Form Body
data.allowed_mentions[MODEL_TYPE_CONVERT]: Expected an object/dictionary.
    at SequentialHandler.runRequest (/home/ocean/devious-disposition/node_modules/@discordjs/rest/dist/index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/ocean/devious-disposition/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/home/ocean/devious-disposition/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async ChatInputCommandInteraction.reply (/home/ocean/devious-disposition/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Object.execute (/home/ocean/devious-disposition/interactions/commands/preregister.js:16:9)
    at async Client.<anonymous> (/home/ocean/devious-disposition/index.js:37:4) {
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { data: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/...',
  requestBody: { files: [], json: { type: 4, data: [Object] } }
}
```
