### ISSUE TITLE
Fix Broken GIF Generation.

### ISSUE THREAD

**Issue by RintaDev5792** [OceanUwU/battlebot#5]
At the end of a game, the bot just says "Generating Gif" instead of generating a gif as it has in the past. Please fix this.

**Comment by OceanUwU** [comment]
```
BOT: rintadev ran /finish
Error: Server responded with 403
    at /home/ocean/devious-disposition/node_modules/canvas/lib/image.js:59:28
    at /home/ocean/devious-disposition/node_modules/simple-get/index.js:89:7
    at IncomingMessage.<anonymous> (/home/ocean/devious-disposition/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by OceanUwU** [comment]
broke because [discord changed the way they host images](https://www.tumblr.com/desktop-assistant/729670550209937408/discord-as-a-filehost-will-no-longer-be-possible). trying a different method of getting the url but it might not work for images older than like a day or so, so @DethDefier let me know if the new gif generation works for the entire history of a game that starts after this fix is implemented
